### ISSUE TITLE
[Bug] The InvalidGuidLenghtException's message is outdated

### ISSUE THREAD

**Issue by Leo-Peyronnet** [Leo-Corporation/LeoCorpLibrary#130]
**Description of the bug:**
The InvalidGuidLenghtException's message is outdated

**How to reproduce the bug:**
Put this line of code:
~~~ cs
string guid = GuidGenerator.Generate(40);
~~~

**Expected behaviour:**
The The InvalidGuidLenghtException is thrown:
~~~
Unhandled exception. LeoCorpLibrary.Exceptions.InvalidGuidLenghtException: The lenght of a Guid must be higher than 0.
   at LeoCorpLibrary.GuidGenerator.Generate(GuidGeneratorParameters guidGeneratorParameters)
   at Program.Main()
~~~
*But the message is the same if the lenght is higher than 32.*

**Computer:**
 - OS: Windows 10
 - OS Version: 10.0.19041.508
 - Software's Version: 2.2.0.2009

**Comment by Leo-Peyronnet** [comment]
**Thursday, September 29th:** The bug has been fixed.
